before yield
Caught: exception 'RuntimeException' with message 'throw' in %s/throw_rethrow.php:16
Stack trace:
#0 {main}


Fatal error: Uncaught exception 'LogicException' with message 'new throw' in %s/throw_rethrow.php:10
Stack trace:
#0 (): gen()
#1 %s/throw_rethrow.php(16): Generator->throw()
#2 {main}
